#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ocamlbuild
Version  : 0.9.3
Release  : 2
URL      : https://github.com/ocaml/ocamlbuild/archive/0.9.3.tar.gz
Source0  : https://github.com/ocaml/ocamlbuild/archive/0.9.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 GPL-2.0 LGPL-2.0
Requires: ocamlbuild-bin
BuildRequires : ocaml
BuildRequires : util-linux

%description
The organization of tests is the following:
- internal.ml contains the tests that should be runnable from a bare
OCaml installation -- always passing the -no-ocamlfind option.

%package bin
Summary: bin components for the ocamlbuild package.
Group: Binaries

%description bin
bin components for the ocamlbuild package.


%prep
%setup -q -n ocamlbuild-0.9.3

%build
export LANG=C
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/ocaml/ocamlbuild/META
/usr/lib64/ocaml/ocamlbuild/ocamlbuild.cmo
/usr/lib64/ocaml/ocamlbuild/ocamlbuild.cmx
/usr/lib64/ocaml/ocamlbuild/ocamlbuild.o
/usr/lib64/ocaml/ocamlbuild/ocamlbuild_executor.cmi
/usr/lib64/ocaml/ocamlbuild/ocamlbuild_executor.cmx
/usr/lib64/ocaml/ocamlbuild/ocamlbuild_executor.o
/usr/lib64/ocaml/ocamlbuild/ocamlbuild_pack.cmi
/usr/lib64/ocaml/ocamlbuild/ocamlbuild_pack.cmx
/usr/lib64/ocaml/ocamlbuild/ocamlbuild_plugin.cmi
/usr/lib64/ocaml/ocamlbuild/ocamlbuild_plugin.cmx
/usr/lib64/ocaml/ocamlbuild/ocamlbuild_plugin.o
/usr/lib64/ocaml/ocamlbuild/ocamlbuild_unix_plugin.cmi
/usr/lib64/ocaml/ocamlbuild/ocamlbuild_unix_plugin.cmx
/usr/lib64/ocaml/ocamlbuild/ocamlbuild_unix_plugin.o
/usr/lib64/ocaml/ocamlbuild/ocamlbuildlib.cma
/usr/lib64/ocaml/ocamlbuild/ocamlbuildlib.cmxa
/usr/lib64/ocaml/ocamlbuild/signatures.mli

%files bin
%defattr(-,root,root,-)
/usr/bin/ocamlbuild
/usr/bin/ocamlbuild.byte
/usr/bin/ocamlbuild.native
